YAPP-Github/20th-ALL-Rounder-Team-1-iOS

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/Presentation/Common/Coordinator/AppCoordinator.swift
Weekand/Weekand/Presentation/Common/Coordinator/CoordinatorType.swift
Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
Weekand/Weekand/Presentation/SignScene/SignIn/Coordinator/SignInCoordinator.swift
Weekand/Weekand/Presentation/SignScene/SignIn/ViewModel/SignInViewModel.swift
Weekand/Weekand/Presentation/SignScene/Welcome/Coordinator/WelcomeCoordinator.swift

Coordinator를 활용해 MainScene 연결

---

Weekand/Weekand/Presentation/Common/View/WCheckBox.swift
Weekand/Weekand/Presentation/Common/View/WDefaultButton.swift
Weekand/Weekand/Presentation/SignScene/SignUp/View/SignUpAddInfomationViewController.swift
Weekand/Weekand/Presentation/SignScene/SignUp/View/SignUpTermsViewController.swift
Weekand/Weekand/Presentation/SignScene/SignUp/View/SignUpViewController.swift
Weekand/Weekand/Presentation/SignScene/SignUp/View/Views/InformationGroupStackView.swift
Weekand/Weekand/Presentation/SignScene/SignUp/View/Views/InputGroupStackView.swift
Weekand/Weekand/Presentation/SignScene/SignUp/ViewModel/SignUpViewModel.swift
Weekand/Weekand/Presentation/Utils/DesignSystem/ColorSet.swift

회원 가입내 이메일, 닉네임 입력 로직 개선

---

Weekand/Podfile.lock
Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand.xcodeproj/xcuserdata/ihoyeong.xcuserdatad/xcschemes/xcschememanagement.plist
Weekand/Weekand/Application/SceneDelegate.swift
Weekand/Weekand/Domain/Category.swift
Weekand/Weekand/Presentation/MainScene/Category/View/CategoryDetailViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/View/MainCalendarView.swift

gitHub web을 이용한 conflict 해결 방법 
---

conflict 대응에 대한 수정사항 반영

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/API.swift
Weekand/Weekand/Domain/Entities/UserSummary.swift
Weekand/Weekand/Networking/Query/UserSummary.graphql

fix: UserSummary 모델이 id를 포함하도록 수정

---

Weekand/Weekand/Domain/UseCase/Sign/SignInUseCase.swift
Weekand/Weekand/Presentation/SignScene/SignIn/ViewModel/SignInViewModel.swift

- SignleTon 내 객체 주입이라 초기 한번만 실행되는 Login 플로우 내 작성
---

사용자 Id 값 넣는 로직 개선  

---

Weekand/Weekand/Presentation/MainScene/Search/View/UserSearchViewController.swift
Weekand/Weekand/Presentation/MainScene/Search/ViewModel/UserSearchViewModel.swift

sorting 하는 부분을 제대로 테스트하지 못햇습니다
---

Search Scene 네트워크 연결 방식 개선

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/Domain/ScheduleEditUseCase.swift
Weekand/Weekand/Domain/UseCase/Main/CategoryUseCase.swift
Weekand/Weekand/Domain/UseCase/Main/SearchUseCase.swift
Weekand/Weekand/Domain/UseCase/Sign/SignInUseCase.swift
Weekand/Weekand/Domain/UseCase/Sign/SignUpUseCase.swift
Weekand/Weekand/Networking/Error/CategoryError.swift
Weekand/Weekand/Networking/Error/SignUpError.swift
Weekand/Weekand/Networking/Query/deleteCategory.graphql
Weekand/Weekand/Presentation/MainScene/Category/Coordinator/CategoryAddCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Category/Coordinator/CategoryCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Category/Coordinator/CategoryModifyCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Category/View/CategoryListViewController.swift
Weekand/Weekand/Presentation/MainScene/Category/ViewModel/CategoryAddViewModel.swift
Weekand/Weekand/Presentation/MainScene/Category/ViewModel/CategoryListViewModel.swift
Weekand/Weekand/Presentation/MainScene/Category/ViewModel/CategoryModifyViewModel.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/Coordinator/ScheduleEditCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/RepeatSheetViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/RepeatTabViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/ScheduleEditViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/Views/DayRepeatViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/Views/MonthRepeatViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/Views/WeekRepeatViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/Views/YearRepeatViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/ViewModel/ScheduleEditViewModel.swift
Weekand/Weekand/Presentation/MainScene/Search/View/UserSearchViewController.swift
Weekand/Weekand/Presentation/MainScene/Search/ViewModel/UserSearchViewModel.swift
Weekand/Weekand/Presentation/SignScene/SignUp/ViewModel/SignUpViewModel.swift

graphql cache 정책에 따른 버그를 발견하여 상황에 맞게 적용하는 법을 배웟습니다
---

네트워크 재요청 시 발생하는 문제 개선

---

Weekand/Weekand/Domain/ScheduleRepeatType.swift
Weekand/Weekand/Domain/ScheduleSummary.swift
Weekand/Weekand/Domain/UseCase/Main/CategoryUseCase.swift
Weekand/Weekand/Networking/Query/SearchSchedules.graphql
Weekand/Weekand/Presentation/MainScene/Category/View/CategoryDetailViewController.swift
Weekand/Weekand/Presentation/MainScene/Category/View/SubView/CategoryDetailToolBar.swift
Weekand/Weekand/Presentation/MainScene/Category/ViewModel/CategoryDetailViewModel.swift
Weekand/Weekand/Presentation/Utils/APIModelExtensions/RepeatType+extension.swift

카테고리 내 일정 검색 기능 구현

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/Data/UserDataStorage.swift
Weekand/Weekand/Domain/Entities/UserSummary.swift
Weekand/Weekand/Domain/KeyChain/KeyChainAccount.swift
Weekand/Weekand/Domain/KeyChain/KeyChainError.swift
Weekand/Weekand/Domain/KeyChain/KeyChainManager.swift
Weekand/Weekand/Domain/ToeknManager.swift
Weekand/Weekand/Domain/UseCase/Sign/SignInUseCase.swift
Weekand/Weekand/Networking/Error/NetworkError.swift
Weekand/Weekand/Networking/Network.swift
Weekand/Weekand/Networking/NetworkInterceptorProvider.swift
Weekand/Weekand/Networking/Query/Reissue.graphql
Weekand/Weekand/Networking/Query/SearchUsers.graphql
Weekand/Weekand/Networking/Query/UserSummary.graphql
Weekand/Weekand/Networking/RefreshTokenInterceptor.swift
Weekand/Weekand/Networking/TokenAddingInterceptor.swift
Weekand/Weekand/Presentation/Common/Coordinator/AppCoordinator.swift
Weekand/Weekand/Presentation/Common/View/WCheckBox.swift
Weekand/Weekand/Presentation/MainScene/Search/ViewModel/UserSearchViewModel.swift
Weekand/Weekand/Presentation/SignScene/SignIn/View/SignInViewController.swift
Weekand/Weekand/Presentation/SignScene/SignIn/ViewModel/SignInViewModel.swift

Access Token, Refresh Token을 이용한 네트워크 Interceptor 개념을 알게 되었습니다
KeyChain에 대해서 공부하게 되었습니다
---

Token을 이용한 로그인 유지 및 자동 로그인 기능 구현 

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/API.swift
Weekand/Weekand/Domain/ProfileUseCase.swift
Weekand/Weekand/Networking/Query/CreateFollowee.graphql
Weekand/Weekand/Networking/Query/DeleteFollowee.graphql
Weekand/Weekand/Presentation/Common/View/WDefaultButton.swift
Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/ProfileViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/ProfileViewModel.swift

ProfileScene 네트워크 연결, 메인화면 어색한 UI 수정

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/Domain/Entities/Category.swift
Weekand/Weekand/Domain/ProfileUseCase.swift
Weekand/Weekand/Domain/ScheduleDetail.swift
Weekand/Weekand/Domain/ScheduleDetailUseCase.swift
Weekand/Weekand/Domain/TokenManager.swift
Weekand/Weekand/Networking/Query/DeleteUser.graphql
Weekand/Weekand/Networking/Query/Logout.graphql
Weekand/Weekand/Networking/Query/Schedule.graphql
Weekand/Weekand/Networking/RefreshTokenInterceptor.swift
Weekand/Weekand/Networking/TokenAddingInterceptor.swift
Weekand/Weekand/Presentation/Common/Coordinator/AppCoordinator.swift
Weekand/Weekand/Presentation/Common/Coordinator/CoordinatorType.swift
Weekand/Weekand/Presentation/Common/ViewController/PopupViewController.swift
Weekand/Weekand/Presentation/MainScene/Category/Coordinator/CategoryCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Category/View/CategoryDetailViewController.swift
Weekand/Weekand/Presentation/MainScene/Category/ViewModel/CategoryDetailViewModel.swift
Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleDetail/Coordinator/ScheduleDetailCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleDetail/View/ScheduleDetailViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleDetail/View/Views/ScheduleCategoryStackView.swift
Weekand/Weekand/Presentation/MainScene/ScheduleDetail/View/Views/ScheduleInformationStackView.swift
Weekand/Weekand/Presentation/MainScene/ScheduleDetail/ViewModel/ScheduleDetailViewModel.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/Coordinator/ProfileCoordinator.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/Coordinator/ResignWarningPopupCoordinator.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/ResignWarningPopupViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/ProfileViewModel.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/WarningPopupViewModel.swift
Weekand/Weekand/Presentation/SignScene/SignIn/ViewModel/SignInViewModel.swift
Weekand/Weekand/Presentation/Utils/APIModelExtensions/ScheduleStatus+extension.swift

로그아웃 및 회원탈퇴, 일정 상세보기 UI 구현

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/API.swift
Weekand/Weekand/Domain/Alarm.swift
Weekand/Weekand/Domain/Entities/FollwingUser.swift
Weekand/Weekand/Domain/ProfileUseCase.swift
Weekand/Weekand/Domain/UseCase/Main/MainUseCase.swift
Weekand/Weekand/Networking/Query/Followees.graphql
Weekand/Weekand/Networking/Query/Followers.graphql
Weekand/Weekand/Networking/Query/Notification.graphql
Weekand/Weekand/Networking/Query/SendContact.graphql
Weekand/Weekand/Networking/Query/UpdatePassword.graphql
Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/AlarmViewModel.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/Coordinator/ProfileCoordinator.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/ContactCompleteViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/ContactViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/PasswordChangeViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/ContactViewModel.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/PasswordChangeViewModel.swift

알람화면, 프로필 수정, 비밀번호 변경

---

Weekand/Weekand/Presentation/MainScene/Search/Coordinator/UserSearchCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Search/View/UserSearchViewController.swift
Weekand/Weekand/Presentation/MainScene/Search/ViewModel/UserSearchViewModel.swift

feat: 유저 검색에서 프로필 화면 연결

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/Domain/UseCase/Main/MainUseCase.swift
Weekand/Weekand/Networking/Apollo/Interceptor/RefreshTokenInterceptor.swift
Weekand/Weekand/Networking/Apollo/Interceptor/RequestLoggingInterceptor.swift
Weekand/Weekand/Networking/Apollo/Interceptor/TokenAddingInterceptor.swift
Weekand/Weekand/Networking/Apollo/Interceptor/‌ResponseLoggingInterceptor.swift
Weekand/Weekand/Networking/Query/SkipSchedule.graphql
Weekand/Weekand/Networking/Timestamp.swift
Weekand/Weekand/Presentation/Common/View/WCalendarView.swift
Weekand/Weekand/Presentation/MainScene/Category/Coordinator/CategoryCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Category/View/CategoryDetailViewController.swift
Weekand/Weekand/Presentation/MainScene/Category/View/CategoryListViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/View/SubView/MainView/MainCalendarView.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
Weekand/Weekand/Presentation/MainScene/ScheduleDetail/Coordinator/ScheduleDetailCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/Coordinator/ScheduleModifyCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/ScheduleEditViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/WeekRepeatViewController.swift

MainViewModel 내 일정 삭제 및 수정 적용 

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/Presentation/Common/Coordinator/AlertPopupCoordinator.swift
Weekand/Weekand/Presentation/Common/ViewController/AlertPopupViewController.swift
Weekand/Weekand/Presentation/Common/ViewController/PopupViewController.swift
Weekand/Weekand/Presentation/Common/ViewModel/AlertPopupViewModel.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/Coordinator/ProfileCoordinator.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/ProfileViewModel.swift

로그아웃 시 팝업을 띄우도록 개선

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/API.swift
Weekand/Weekand/Domain/UseCase/Main/MainUseCase.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
Weekand/Weekand/schema.json

메인화면 자동 새로고침 개선

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/Domain/Enum/CategoryOpenType.swift
Weekand/Weekand/Presentation/Common/Coordinator/AlertPopupCoordinator.swift
Weekand/Weekand/Presentation/Common/Coordinator/CoordinatorType.swift
Weekand/Weekand/Presentation/MainScene/Category/Coordinator/CategoryModifyCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Category/View/CategoryEditViewController.swift
Weekand/Weekand/Presentation/MainScene/Category/View/ColorSheetViewController.swift
Weekand/Weekand/Presentation/MainScene/Category/View/SubView/OpenTypeCollectionViewCell.swift
Weekand/Weekand/Presentation/MainScene/Category/View/SubView/OpenTypeStackView.swift
Weekand/Weekand/Presentation/MainScene/Category/ViewModel/CategoryAddViewModel.swift
Weekand/Weekand/Presentation/MainScene/Category/ViewModel/CategoryModifyViewModel.swift
Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/Coordinator/ScheduleAddCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/Coordinator/ScheduleModifyCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/ScheduleEditViewController.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/Views/CategoryStackView.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/Views/DateStackView.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/Views/TimeStackView.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/ViewModel/DefaultRepeatViewModel.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/ViewModel/ScheduleAddViewModel.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/ViewModel/ScheduleModifyViewModel.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/ViewModel/WeekRepeatViewModel.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/Coordinator/ProfileCoordinator.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/ProfileViewModel.swift
Weekand/Weekand/Presentation/SignScene/SignUp/View/SignUpAddInfomationViewController.swift

카테고리 공개 상태 오류 개선 및 

---

Weekand/Weekand/Domain/Enum/Status.swift
Weekand/Weekand/Presentation/Common/Coordinator/CoordinatorType.swift
Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/ScheduleEdit/Coordinator/ScheduleAddCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Search/View/SubView/UserTableViewCell.swift

메인 일정 관련 개선사항 적용

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/API.swift
Weekand/Weekand/Domain/ProfileUseCase.swift
Weekand/Weekand/Networking/Query/DeleteFollower.graphql
Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/FollowViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/FollowViewModel.swift

남의 일정 swipe 차단, 팔로워 삭제 기능 구현

---

Weekand/Weekand/Presentation/ProfileScene/Profile/View/FollowViewController.swift

fix: 팔로우 목록에서 항목 선택 후 selection 해제

---

Weekand/Weekand/Networking/ImageUploader.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/ProfileEditViewModel.swift

feat: 프로필 사진 업로드 구현

---

Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
Weekand/Weekand/Presentation/MainScene/ScheduleDetail/View/ScheduleDetailViewController.swift

일정이 undetermined인 경우 완료, 미완료 가능하도록 개선

---

Weekand/Weekand/Presentation/MainScene/Main/Coordinator/MainCoordinator.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift

팔로우의 일정 완료, 미완료 처리 할수없도록 개선

---

Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/View/SubView/MainView/MainTableViewCell.swift

일정 스킵, 이후 모든일정 삭제 기능 적용

---

Weekand/Weekand/Presentation/ProfileScene/Profile/View/PasswordChangeViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/ProfileEditViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/ProfileEditViewModel.swift
Weekand/Weekand/Presentation/SignScene/SignIn/View/SignInViewController.swift
Weekand/Weekand/Presentation/SignScene/SignUp/View/SignUpViewController.swift
Weekand/Weekand/Resources/Info.plist

프로필 사진 앨범권한 alert 구현, 이메일 textField 키보드 수정

---

Weekand/Weekand/Domain/Alarm.swift
Weekand/Weekand/Domain/ProfileUseCase.swift
Weekand/Weekand/Domain/UseCase/Main/MainUseCase.swift
Weekand/Weekand/Presentation/MainScene/Main/View/AlarmViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/View/SubView/AlarmTableViewCell.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/AlarmViewModel.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/FollowViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/ViewModel/FollowViewModel.swift

알람 화면, 팔로워/팔로잉 목록 화면, 메인화면 팔로잉 목록 Pagination

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/Presentation/MainScene/Main/View/MainScheduleDataSource.swift
Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/View/Sheet/StickerAddSheet.swift
Weekand/Weekand/Presentation/MainScene/Main/View/SubView/MainView/MainCollectionViewCell.swift
Weekand/Weekand/Presentation/MainScene/Main/View/SubView/MainView/MainProfileView.swift
Weekand/Weekand/Presentation/MainScene/Main/View/SubView/Sheet/EmojiTableViewCell.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/Sheet/EmojiTableViewModel.swift
Weekand/Weekand/Presentation/MainScene/Search/View/SubView/UserTableViewCell.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/ProfileEditViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/ProfileViewController.swift
Weekand/Weekand/Presentation/Utils/Manager/ImageCacheManager.swift

이미지 캐싱 처리 및 메인 일정 리스트 스와이프 적용

---

Weekand/Weekand/Presentation/MainScene/ScheduleEdit/View/ScheduleEditViewController.swift
Weekand/Weekand/Presentation/ProfileScene/Profile/View/SubView/FollowTableViewCell.swift

팔로워, 팔로잉 리스트 이미지 캐싱처리 및 일정 추가 시 시간값 보정 기능 추가

---

Weekand/Weekand/Application/SceneDelegate.swift
Weekand/Weekand/Presentation/MainScene/Category/View/CategoryEditViewController.swift
Weekand/Weekand/Presentation/Utils/Extensions/UIVIewController+modality.swift

AppLifeCycle 관련 오류 및 UI 개선사항 적용

---

Weekand/Weekand.xcodeproj/project.pbxproj
Weekand/Weekand/API.swift
Weekand/Weekand/Domain/UseCase/Main/MainUseCase.swift
Weekand/Weekand/Networking/Query/MyStickerAdded.graphql
Weekand/Weekand/Presentation/MainScene/Main/View/Sheet/MonthlyCalendarSheet.swift
Weekand/Weekand/Presentation/MainScene/Main/View/Sheet/StickerAddSheet.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/Sheet/StickerAddSheetViewModel.swift

스티커 추가시 기존 스티커 확인 기능, 월간 달력 이슈 해결

---

Weekand/Weekand/Presentation/MainScene/Main/View/MainViewController.swift
Weekand/Weekand/Presentation/MainScene/Main/ViewModel/MainViewModel.swift

다른 화면에서 돌아오면 팔로잉 목록에 Selection 테두라가 사라지는 문제 #180
